import Head from 'next/head';
import Image from 'next/image';
import Cards from '../components/Cards';
import History from '../components/History';
import Navbar from '../components/Navbar';
import SearchBar from '../components/SearchBar';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bridge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />
      <div style={{ padding: '24px 50px 50px 50px' }}>
        <SearchBar />
        <Cards />

        <div style={{ marginTop: '56px', display: 'flex', columnGap: '16px' }}>
          <History name='Latest Transactions' data={[1, 2, 3, 4, 5, 6]} />
          <History name='Pending Transactions' data={[1, 2, 3, 4, 5, 6]} />
        </div>
      </div>
    </div>
  );
}
